name: 'Clone Github Repo Action'

description: "Github Action to clone a public or private Github repository and access its content on others repositories' workflows."

inputs:
  owner:
    description: 'Repository Owner'
    required: true
  repository:
    description: 'Repository name'
    required: true
  access-token:
    description: 'PAT with repository scope (https://github.com/settings/tokens)'
    required: false
  branch:
    description: 'Repository Branch'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Missing required value
      if: ${{ github.event.inputs.owner == '' || github.event.inputs.repository == '' }}
      run: echo "Missing Required Value!"
      shell: bash
    - name: Clone repository
      if: ${{ github.event.inputs.owner != '' && github.event.inputs.repository != '' }}
      run: |
        if [[ -z ${{ github.event.inputs.access-token }} && -z ${{ github.event.inputs.branch }} ]]; then
          git clone https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
        elif [[ -z ${{ github.event.inputs.access-token }} && -n ${{ github.event.inputs.branch }} ]]; then
          git clone https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git -b ${{ inputs.branch }}
        elif [[ -n ${{ github.event.inputs.access-token }} && -z ${{ github.event.inputs.branch }} ]]; then
          git clone https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git
        else
          git clone https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git -b ${{ inputs.branch }}
      shell: bash

branding:
  icon: 'download'
  color: 'blue'