name: 'Clone Github Repo Action'

description: "Github Action to clone a public or private Github repository and access its content on others repositories' workflows."

inputs:
    owner:
        description: 'Repository Owner'
        required: true
    repository:
        description: 'Repository name'
        required: true
    access-token:
        description: 'PAT with repository scope (https://github.com/settings/tokens)'
        required: false
    path-to-clone:
        description: 'PATH to clone the repository to.'
        required: false

runs:
    using: 'composite'
    steps:
    - uses: actions/checkout@v3
    - name: Clone repository
      run: |
        if [ -z "${{ inputs.path-to-clone }}" ]; then
            echo "No path to clone provided."
        else
            if [ ! -d "${{ inputs.path-to-clone }}" ]; then
                mkdir ${{ inputs.path-to-clone }}
                if [ ! -d "${{ inputs.path-to-clone }}" ]; then
                    echo "PATH ${{ inputs.path-to-clone }} DOES NOT exist in the workspace: ${{ github.workspace }} and couldn't be created automatically."
                    exit 1
            fi
        fi
        
        if [ -z "${{ inputs.access-token }}" ]; then
            git clone https://github.com/${{ inputs.owner }}/${{ inputs.repository }}.git ${{ inputs.path-to-clone }}
        else
            git clone https://${{ inputs.access-token }}@github.com/${{ inputs.owner }}/${{ inputs.repository }}.git ${{ inputs.path-to-clone }}
        fi

        if [ -d "${{ inputs.repository }}" ] || [ -d "${{ inputs.path-to-clone }}" ]; then
            echo "Cloned ${{ inputs.repository }} repository successfully."
            if [ -z "${{ inputs.path-to-clone }}" ]; then
                echo "Access the repository content using \"cd ${{ inputs.repository }}\"."
            else
                echo "Access the repository content using \"cd ${{ inputs.path-to-clone }}\"."
            fi 
        else
            echo "Error: Couldn't clone ${{ inputs.repository }} repository. Check the inputs or the PAT scope."
            exit 1
        fi
      shell: bash

branding:
    icon: 'download'
    color: 'blue'
