name: Action test on Ubuntu

on:
  push:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd poc-github-actions
          ls -la
    
  job-private-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'formulas-training'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd formulas-training
          ls -la

  job-PATH-ERROR:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
          path-to-clone: 'path/to/clone'

  job-PATH-SUCCESS:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir path/to/clone   
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
          path-to-clone: 'path/to/clone'