name: Action test on Windows

on:
  push:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  job-public-repo-windows:
    runs-on: windows-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd poc-github-actions
          ls -la
        shell: bash
    
  job-private-repo-windows:
    runs-on: windows-latest
    steps:
      
      - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'formulas-training'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd formulas-training
          ls -la
        shell: bash

  job-with-path:
    runs-on: windows-latest
    steps:
      
      - run: |
          mkdir path
          cd path
          mkdir to
          cd to
          mkdir clone
          cd clone          
        shell: bash
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v3
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
          path-to-clone: 'path/to/clone'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd path/to/clone
          ls -la
        shell: bash
